### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by SylvainGa** [iz0qwm/ecowitt_http_gateway#2]
On a Buster raspbian installation, I get 

```
Jul 19 22:34:58 raspberrypi weewx[22194] CRITICAL __main__:     ****      self.setupStation(config_dict)
Jul 19 22:34:58 raspberrypi weewx[22194] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation
Jul 19 22:34:58 raspberrypi weewx[22194] CRITICAL __main__:     ****      __import__(driver)
Jul 19 22:34:58 raspberrypi weewx[22194] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/ecowitt.py", line 137
Jul 19 22:34:58 raspberrypi weewx[22194] CRITICAL __main__:     ****      self.mode = stn_dict.get('mode')
Jul 19 22:34:58 raspberrypi weewx[22194] CRITICAL __main__:     ****                                      ^
Jul 19 22:34:58 raspberrypi weewx[22194] CRITICAL __main__:     ****  TabError: inconsistent use of tabs and spaces in indentation
Jul 19 22:34:58 raspberrypi weewx[22194] CRITICAL __main__:     ****  Exiting.
```

When starting weewx. 

I replaced many until I got to line 333 where I now get the following error:
```
Jul 19 22:30:37 raspberrypi weewx[22000] CRITICAL __main__:     ****      self.setupStation(config_dict)
Jul 19 22:30:37 raspberrypi weewx[22000] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation
Jul 19 22:30:37 raspberrypi weewx[22000] CRITICAL __main__:     ****      __import__(driver)
Jul 19 22:30:37 raspberrypi weewx[22000] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/ecowitt.py", line 333
Jul 19 22:30:37 raspberrypi weewx[22000] CRITICAL __main__:     ****      except (ValueError, IndexError), e:
Jul 19 22:30:37 raspberrypi weewx[22000] CRITICAL __main__:     ****                                     ^
Jul 19 22:30:37 raspberrypi weewx[22000] CRITICAL __main__:     ****  SyntaxError: invalid syntax
Jul 19 22:30:37 raspberrypi weewx[22000] CRITICAL __main__:     ****  Exiting.
Jul 19 22:30:37 raspberrypi weewx[21983]: Starting weewx weather system: weewx.
Jul 19 22:30:37 raspberrypi systemd[1]: Started LSB: weewx weather system.
```

python --version 
returns Python 2.7.16

python3 --version
returns Python 3.7.3

Do you know what I'm doing wrong?

Thanks

**Comment by iz0qwm** [comment]
Hi SylvainGa,
thank you for reporting.
Now I'm not at home with a raspberry but if you try to upload the ecowitt.py to this page:
[https://www.tutorialspoint.com/online_python_formatter.htm](url)

It will format for you. And you can download the new file.  

Attached you find the **new ecowitt.py**

[ecowitt.zip](https://github.com/iz0qwm/ecowitt_http_gateway/files/4945463/ecowitt.zip)


Please can you test it?

**Comment by SylvainGa** [comment]
As I expected since I did fix the formatting error myself previously, I now get the same error as the last time:

```
Jul 22 22:36:25 raspberrypi weewx[21341] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation
Jul 22 22:36:25 raspberrypi weewx[21341] CRITICAL __main__:     ****      __import__(driver)
Jul 22 22:36:25 raspberrypi weewx[21341] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/ecowitt.py", line 124
Jul 22 22:36:25 raspberrypi weewx[21341] CRITICAL __main__:     ****      except ValueError, e:
Jul 22 22:36:25 raspberrypi weewx[21341] CRITICAL __main__:     ****                       ^
Jul 22 22:36:25 raspberrypi weewx[21341] CRITICAL __main__:     ****  SyntaxError: invalid syntax
Jul 22 22:36:25 raspberrypi weewx[21341] CRITICAL __main__:     ****  Exiting.
Jul 22 22:36:25 raspberrypi weewx[21325]: Starting weewx weather system: weewx.
Jul 22 22:36:25 raspberrypi systemd[1]: Started LSB: weewx weather system.
```

That's the reason I posted my Python version in my first post. They are:

python --version
returns Python 2.7.16

python3 --version
returns Python 3.7.3

**Comment by iz0qwm** [comment]
Ok now I understand.
I'm using an old way except **ValueError, e:** was the syntax used for what is normally written as **except ValueError as e:**
As described here:
https://docs.python.org/2/tutorial/errors.html

Now the error you see is different then before. Now the row is 124, before was on 133

Please try to change the **_row 124_**

from
**except ValueError, e:**
to
**except ValueError as e:**

And **_row 133_**

from
**except (ValueError, IndexError), e:**
to
**except (ValueError, IndexError) as e:**


_**NOTE:**
**It seems that is the online formatter that changes that except row.**_

**Comment by SylvainGa** [comment]
So this fixes that error (although there was others 'except ..., e' that I replaced for 'except ... as e'). Now I get the following:

```
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 69, in __init__
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****      self.setupStation(config_dict)
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****      __import__(driver)
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/ecowitt.py", line 461
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****      print weeutil.weeutil.timestamp_to_string(packet['dateTime']), \
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****                  ^
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****  SyntaxError: invalid syntax
Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****  Exiting.
```

Not sure what to do here. Thanks

**Comment by SylvainGa** [comment]
So since that code is simply to test the driver, I commented it out to see if it would finally start, now I get that error:

```
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 148, in main
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 69, in __init__
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****      self.setupStation(config_dict)
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 92, in setupStation
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****      __import__(driver)
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/ecowitt.py", line 83, in <module>
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****      import BaseHTTPServer
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****  ModuleNotFoundError: No module named 'BaseHTTPServer'
Jul 23 22:19:05 raspberrypi weewx[1058] CRITICAL __main__:     ****  Exiting.
```

**Comment by iz0qwm** [comment]
> So this fixes that error (although there was others 'except ..., e' that I replaced for 'except ... as e'). Now I get the following:

> Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/ecowitt.py", line 461
> Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****      print weeutil.weeutil.timestamp_to_string(packet['dateTime']), \
> Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****                  ^
> Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****  SyntaxError: invalid syntax
> Jul 23 22:03:31 raspberrypi weewx[416] CRITICAL __main__:     ****  Exiting.
> ```
> 
> Not sure what to do here. Thanks

That is because in Python 3, they have replaced the print statement with the print function.

--------------------------------------------------------------------------------------------------------------------------------------

Now you have to install all the needed modules with python. The code has been written for python 2.
With python3 it's necessary to use the 2to3 software.
You install the modules with  pip install <modulename> (i.e. pip install BaseHTTPServer )

These are the modules requested by the driver.

import syslog
import time
import BaseHTTPServer
import SocketServer
import re
import Queue
import threading
import urlparse

**Due to all the syntax errors I think you're using python3. Please, the code has been writte for python 2.7.x**
In python3 BaseHTTPServer is inside httpsserver I think you have to change also this import

**Comment by SylvainGa** [comment]
Hi, yes, I do have Python3 installed, but also Python2 and it's the default, as shown by 

python --version
Python 2.7.16

and

ls -l /usr/bin/python
lrwxrwxrwx 1 root root 7 Mar  4  2019 /usr/bin/python -> python2

There is no alias pointing to python3 in neither pi or root.

However, I do run Home Assistant on that same pi. Maybe since that one uses Python3 and it's loaded, it defaults to that instance?

**Comment by SylvainGa** [comment]
Found this in /usr/bin/weewxd

WEEWX_PYTHON=python3

Explains why ecowitt wants to run in Python3

**Comment by SylvainGa** [comment]
Tried 2to3 but the code it generated gave me this error:

```
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 154, in main
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****      engine.run()
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 188, in run
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****      for packet in self.console.genLoopPackets():
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/ecowitt.py", line 301, in genLoopPackets
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****      self._augment_packet(_packet)
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/ecowitt.py", line 445, in _augment_packet
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****      weewx.wxformulas.calculate_rain(packet['rain_total'],
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****  KeyError: 'rain_total'
Jul 28 00:38:37 raspberrypi weewx[9084] CRITICAL __main__:     ****  Exiting.
```

So I gave up and looked for an alternative method to hook my ecowitt to weewx. Found Matthewwall's Interceptor integration. Followed its installation procedure and it is now up and running.

Thank you for your time helping me trying to troubleshoot this. Much appreciated.
